[package]
# name matches ENCLAVE_CARGO_LIB in Makefile
name = "sgx-wallet-enclave"
version = "0.1.0"
edition = "2018"
authors = ["Registree"]

[lib]
crate-type = ["staticlib"]
test = false

[features]
default = []

[dependencies]
sgx_types = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", rev = "d107bd0718f723221750a4f2973451b386cbf9d2" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", features = ["backtrace"], rev = "d107bd0718f723221750a4f2973451b386cbf9d2" }

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
