[package]
# name matches APP_U in Makefile
name = "sgx-wallet-app"
version = "0.1.0"
edition = "2018"
authors = ["Registree"]
build = "build.rs"

[dependencies]
sgx_types = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", rev = "d107bd0718f723221750a4f2973451b386cbf9d2" }
sgx_urts = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", rev = "d107bd0718f723221750a4f2973451b386cbf9d2" }

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
