
services:

  redis:
    image: 'redis:6-alpine'
    ports:
      - '127.0.0.1:6379:6379'

  api:
    depends_on:
      - redis
    build:
      context: .
      target: run-asset-services-api
    read_only: true
    init: true
    environment:
      BROKER_URL: "redis://redis:6379"
      BIND_ADDR: "0.0.0.0:8081"
      RUST_LOG: "info"
    ports:
      - "8081:8081"

  worker:
    depends_on:
      - redis
    build:
      context: .
      target: run-asset-services-worker
    read_only: true
    init: true
    environment:
      BROKER_URL: "redis://redis:6379"
