/* automatically generated by rust-bindgen 0.59.1 */

use sgx_types::*;

extern "C" {
    pub fn ecall_test(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        some_string: *const u8,
        len: size_t,
    ) -> sgx_status_t;
}
