import { RouterTestingModule } from "@angular/router/testing";
import { IonicModule } from "@ionic/angular";
import { setCompodocJson } from "@storybook/addon-docs/angular";
import { componentWrapperDecorator, moduleMetadata } from "@storybook/angular";
// Generated by the docs:json / storybook npm run commands:
import docJson from "../documentation/documentation.json";

setCompodocJson(docJson);

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  docs: { inlineStories: true },
};

// Provide context for Ionic components
export const decorators = [
  // See AppModule:
  moduleMetadata({
    imports: [IonicModule.forRoot(), RouterTestingModule],
  }),
  // See AppComponent's template:
  componentWrapperDecorator(
    (story) => `
      <ion-app>
        <ion-router-outlet>${story}</ion-router-outlet>
      </ion-app>
    `
  ),
];
